import Link from 'next/link';
import { PageHeader } from '@/components/ui/page-header';
import { StatusBadge } from '@/components/ui/status-badge';
import { getCurrentAccess } from '@/lib/auth/access';
import { hasPermission } from '@/lib/auth/permissions';
import { createServerSupabaseClient } from '@/lib/supabase/server';
import { listJobs } from '@/lib/sales/queries';
type SearchParams = Record<string, string | string[] | undefined>;
const one = (value: string | string[] | undefined) => Array.isArray(value) ? value[0] : value;
const statuses = ['new','scheduled','in_progress','waiting','completed','cancelled'];
export default async function JobsPage({ searchParams }: { searchParams: Promise<SearchParams> }) { const access = await getCurrentAccess(); if (!hasPermission(access, 'jobs.view')) return <div className="operations-page"><PageHeader title="Jobs" subtitle="Permission denied" /></div>; const raw = await searchParams; const status = statuses.includes(one(raw.status) ?? '') ? one(raw.status) : undefined; const query = one(raw.q) ?? ''; let rows: Record<string, unknown>[] = []; let error = false; try { rows = await listJobs(await createServerSupabaseClient(), access.locationId, status, query); } catch { error = true; } return <div className="operations-page max-w-6xl"><PageHeader title="Workshop jobs" subtitle="Search and manage branch-scoped workshop work" actions={hasPermission(access, 'jobs.create') ? <Link href="/jobs/new" className="flex h-10 items-center rounded-md bg-primary px-4 text-sm text-primary-foreground">New job</Link> : null} /><form className="flex flex-wrap gap-3 rounded-xl border bg-card p-4" role="search"><input name="q" defaultValue={query} placeholder="Job number, customer or registration" className="h-10 min-w-52 flex-1 rounded-md border border-input bg-background px-3 text-sm" /><select name="status" defaultValue={status ?? ''} className="h-10 rounded-md border border-input bg-background px-3 text-sm"><option value="">All statuses</option>{statuses.map(value => <option key={value} value={value}>{value.replaceAll('_',' ')}</option>)}</select><button className="h-10 rounded-md bg-secondary px-4 text-sm font-medium">Search</button></form>{error ? <div className="mt-5 rounded-xl border border-destructive/40 p-5 text-sm">Jobs could not be loaded.</div> : rows.length === 0 ? <div className="mt-5 rounded-xl border p-8 text-sm text-muted-foreground">No jobs match this view.</div> : <div className="mt-5 grid gap-3">{rows.map(row => <Link key={String(row.id)} href={`/jobs/${row.id}`} className="rounded-xl border bg-card p-4 hover:border-primary"><div className="flex flex-wrap items-center justify-between gap-3"><span className="font-semibold">{String(row.job_number)}</span><StatusBadge status={String(row.status)}>{String(row.status).replaceAll('_',' ')}</StatusBadge></div><div className="mt-2 flex flex-wrap gap-x-4 gap-y-1 text-sm text-muted-foreground"><span>{String(row.customer_name ?? 'Walk-in')}</span><span>{String(row.vehicle_registration ?? 'No vehicle')}</span><span>{row.pricing_complete ? `$${Number(row.total_incl_gst ?? 0).toFixed(2)} incl GST` : 'PRICE PENDING'}</span></div></Link>)}</div>}</div>; }
