import { notFound } from 'next/navigation';
import { PageHeader } from '@/components/ui/page-header';
import { getCurrentAccess } from '@/lib/auth/access';
import { hasPermission } from '@/lib/auth/permissions';
import { createServerSupabaseClient } from '@/lib/supabase/server';
import { transitionQuoteAction, convertQuoteAction } from '../actions';

export default async function QuotePage({ params }: { params: Promise<{ id: string }> }) {
  const access = await getCurrentAccess(); if (!hasPermission(access, 'quotes.view')) return <PageHeader title="Quote" subtitle="Permission denied" />;
  const { id } = await params; const { data, error } = await (await createServerSupabaseClient()).rpc('quote_detail', { p_quote_id: id }); if (error || !data) notFound();
  const actions = data.status === 'draft' ? <div className="flex flex-wrap gap-2"><a href={`/quotes/${id}/edit`} className="flex h-10 items-center rounded-md border px-4 text-sm">Edit</a><form action={transitionQuoteAction.bind(null, id, data.version, 'sent')}><button className="h-10 rounded-md bg-primary px-4 text-sm text-primary-foreground">Send quote</button></form><form action={transitionQuoteAction.bind(null, id, data.version, 'cancelled')}><button className="h-10 rounded-md border px-4 text-sm">Cancel</button></form></div> : data.status === 'sent' ? <div className="flex flex-wrap gap-2"><form action={transitionQuoteAction.bind(null, id, data.version, 'accepted')}><button className="h-10 rounded-md bg-primary px-4 text-sm text-primary-foreground">Accept</button></form><form action={transitionQuoteAction.bind(null, id, data.version, 'declined')}><button className="h-10 rounded-md border px-4 text-sm">Decline</button></form></div> : data.status === 'accepted' ? <div className="flex flex-wrap gap-2"><form action={convertQuoteAction.bind(null, id, data.version)}><button className="h-10 rounded-md bg-primary px-4 text-sm text-primary-foreground">Convert to job</button></form><form action={transitionQuoteAction.bind(null, id, data.version, 'cancelled')}><button className="h-10 rounded-md border px-4 text-sm">Cancel</button></form></div> : null;
  return <div className="operations-page max-w-5xl"><PageHeader title={data.quote_number} subtitle={`${data.customer_snapshot?.display_name ?? 'Customer'} · ${String(data.status).replaceAll('_', ' ')}`} actions={actions} /><div className="grid gap-3 rounded-xl border bg-card p-5">{(data.lines ?? []).map((line: Record<string, unknown>) => <div key={String(line.id)} className="flex justify-between border-b py-2 text-sm last:border-0"><span>{String(line.description)} · {String(line.quantity)}</span><span>{line.unit_price_incl_gst == null ? 'PRICE PENDING' : `$${Number(line.line_total_incl_gst).toFixed(2)}`}</span></div>)}<div className="pt-3 text-right font-semibold">{data.total_incl_gst == null ? 'PRICE PENDING' : `$${Number(data.total_incl_gst).toFixed(2)} incl GST`}</div></div></div>;
}
