import Link from 'next/link';
import { notFound } from 'next/navigation';
import { QuoteEmailForm } from '@/components/quotes/quote-email-form';
import { QuotePrintButton } from '@/components/quotes/quote-print-button';
import { PageHeader } from '@/components/ui/page-header';
import { getCurrentAccess } from '@/lib/auth/access';
import { hasPermission } from '@/lib/auth/permissions';
import { createServerSupabaseClient } from '@/lib/supabase/server';
import { transitionQuoteAction, convertQuoteAction } from '../actions';
import { getQuoteEmailSendStatus } from '@/lib/email/quote-send-status';

export default async function QuotePage({ params }: { params: Promise<{ id: string }> }) {
  const access = await getCurrentAccess(); if (!hasPermission(access, 'quotes.view')) return <PageHeader title="Quote" subtitle="Permission denied" />;
  const { id } = await params; const { data, error } = await (await createServerSupabaseClient()).rpc('quote_detail', { p_quote_id: id }); if (error || !data) notFound();
  const snapshot = (data.contact_snapshot ?? data.customer_snapshot ?? {}) as Record<string, unknown>;
  const recipient = String(snapshot.email ?? (data.customer_snapshot as Record<string, unknown> | undefined)?.accounts_email ?? (data.customer_snapshot as Record<string, unknown> | undefined)?.billing_email ?? (data.customer_snapshot as Record<string, unknown> | undefined)?.email ?? '');
  const actions = <div className="flex flex-wrap gap-2"><Link href={`/quotes/${id}`} className="flex h-10 items-center rounded-md border px-4 text-sm">View Quote</Link><QuotePrintButton /><a href={`/quotes/${id}/pdf`} className="flex h-10 items-center rounded-md border px-4 text-sm" download>Download PDF</a><Link href={`/quotes/${id}/edit`} className="flex h-10 items-center rounded-md border px-4 text-sm">Edit</Link>{data.status === 'draft' ? <><form action={transitionQuoteAction.bind(null, id, data.version, 'sent')}><button className="h-10 rounded-md border px-4 text-sm">Mark as sent</button></form><form action={transitionQuoteAction.bind(null, id, data.version, 'cancelled')}><button className="h-10 rounded-md border px-4 text-sm">Cancel</button></form></> : null}{data.status === 'sent' ? <><form action={transitionQuoteAction.bind(null, id, data.version, 'accepted')}><button className="h-10 rounded-md bg-primary px-4 text-sm text-primary-foreground">Accept</button></form><form action={transitionQuoteAction.bind(null, id, data.version, 'declined')}><button className="h-10 rounded-md border px-4 text-sm">Decline</button></form></> : null}{data.status === 'accepted' ? <form action={convertQuoteAction.bind(null, id, data.version)}><button className="h-10 rounded-md bg-primary px-4 text-sm text-primary-foreground">Convert to job</button></form> : null}</div>;
  return <div className="operations-page max-w-5xl"><PageHeader title={data.quote_number} subtitle={`${snapshot.display_name ?? 'Customer'} · ${String(data.status).replaceAll('_', ' ')}`} actions={actions} /><div className="grid gap-4 lg:grid-cols-[2fr_1fr]"><div className="grid gap-3 rounded-xl border bg-card p-5">{(data.lines ?? []).map((line: Record<string, unknown>) => <div key={String(line.id)} className="flex justify-between border-b py-2 text-sm last:border-0"><span>{String(line.description)} · {String(line.quantity)} · {String(line.pricing_tier ?? 'retail')}</span><span>{line.unit_price_incl_gst == null ? 'PRICE PENDING' : `$${Number(line.line_total_incl_gst).toFixed(2)}`}</span></div>)}<div className="space-y-1 pt-3 text-right text-sm"><p>Subtotal (ex GST): {data.subtotal_ex_gst == null ? 'PRICE PENDING' : `$${Number(data.subtotal_ex_gst).toFixed(2)}`}</p><p>GST: {data.gst_amount == null ? 'PRICE PENDING' : `$${Number(data.gst_amount).toFixed(2)}`}</p><p className="font-semibold">Total incl GST: {data.total_incl_gst == null ? 'PRICE PENDING' : `$${Number(data.total_incl_gst).toFixed(2)}`}</p></div></div>{data.total_incl_gst != null ? <QuoteEmailForm quoteId={id} recipient={recipient} quoteNumber={String(data.quote_number)} total={String(data.total_incl_gst)} sendStatus={await getQuoteEmailSendStatus(id)} /> : null}</div></div>;
}
